version: '3.5'

services:
    nginx:
        image: nginx
        container_name: atlant_nginx
        restart: always
        working_dir: /var/www/atlant/
        volumes:
            - ./:/var/www/atlant
            - ./docker/nginx/:/etc/nginx/conf.d
        ports:
            - 89:80

    php:
        container_name: atlant_php
        restart: always
        working_dir: /var/www/atlant/
        build:
            context: docker/php
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/atlant
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/z-php.ini
        ports:
            - 9009:9000

    mysql:
        container_name: atlant_mysql
        restart: always
        image: mysql
        environment:
            MYSQL_USER: atlant_u
            MYSQL_DATABASE: atlant_db
            MYSQL_PASSWORD: 123456
            MYSQL_ROOT_PASSWORD: 123456
        volumes:
            - atlant-mysql:/var/lib/mysql
        ports:
            - 3309:3306

volumes:
    atlant-mysql:
        external: true
